GRCh38_REFERENCE: '/home/users/pjh/References/reference_genome/GRCh38/GCA_for_alignment_pipelines/no_alt_plus_hs38d1/GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fasta' #/home/users/cjyoon/Projects/mosaic/reference/Homo_sapiens_assembly38.fasta'
GRCh37_REFERENCE: '/home/users/cjyoon/reference/GRCh37/hs37d5.fa'
SAMBLASTER: '/usr/local/bin/samblaster' #v0.1.24
BWA: '/home/users/cjyoon/tools/bwa-0.7.12/bwa' #v0.7.12
SAMTOOLS: '/home/users/cjyoon/anaconda3/bin/samtools' #v1.9
SAMBAMBA: '/home/users/cjyoon/anaconda3/bin/sambamba' #v0.6.6
JAVA: '/home/users/cjyoon/anaconda3/bin/java' #v1.8
GATK: '/home/users/cjyoon/tools/GenomeAnalysisTK-3.8-1/GenomeAnalysisTK.jar'
GRCh38_KNOWNINDEL: '/home/users/cjyoon/reference/GRCh38/Mills_and_1000G_gold_standard.indels.hg38.vcf'
GRCh37_KNOWNINDEL: '/home/users/cjyoon/reference/GRCh37/Mills_and_1000G_gold_standard.indels.b37.vcf'
